name: MongoDB Backup to Google Drive

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install MongoDB Database Tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.4.tgz
          tar -xzf mongodb-database-tools-ubuntu2204-x86_64-100.9.4.tgz
          sudo cp mongodb-database-tools-ubuntu2204-x86_64-100.9.4/bin/* /usr/local/bin/

      - name: Create MongoDB Backup
        run: |
          DATE=$(date +"%Y-%m-%d")
          mongodump --uri="${{ secrets.MONGO_URI }}" --archive=backup-$DATE.gz --gzip
          echo "BACKUP_FILE=backup-$DATE.gz" >> $GITHUB_ENV

      - name: Verify Backup File
        run: |
          ls -lh

      - name: Upload Backup to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: ${{ env.BACKUP_FILE }}
          folderId: "1uF76YzP_Y1A7xZ_C_mVkrDnATBJqztlV"
